# -*- coding: utf-8 -*-
"""Streamlit_linear.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ptrZU6puq7qLg-nH2YjA2Mm0tL4kSrhK
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
data=pd.read_excel("/content/house_prices_100.xlsx")
print(data.head())
x=data[['SquareFootage']]
y=data['Price']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
model=LinearRegression()
model.fit(x_train,y_train)
print("Training Data :")
print(pd.concat([x_train,y_train],axis=1).head())
print("Testing Data :")
print(pd.concat([x_test,y_test],axis=1).head())
y_pred=model.predict(x_test)
plt.figure(figsize=(8,6))
plt.scatter(x_test,y_test,color='green',label='Actual Prices')
plt.plot(x_test,y_pred,color='red',label='Regression Line')
plt.xlabel('Square Footage')
plt.ylabel('Price')
plt.title('Simple Linear Regression : Actual Vs Predicted Price')
plt.legend()
plt.show()
new_house_sqft=pd.DataFrame({'SquareFootage':[2000]})
predict_price=model.predict(new_house_sqft)
print(f"\nPredicted Price For 2000 sqft House : {predict_price}")